apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flask-test
spec: 
  replicas: 1
  template:
    metadata:
      labels:
        app: flask-test
    spec:
      containers:
      - name: integration-poc
        image: chetancheths/first_test:2.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5158
      
